package com.birbit.android.livecode.twitter.vo;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User extends UserBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public User() {
    }

    public User(String id) {
        super(id);
    }

    public User(String id, String description, Boolean following, String screenName) {
        super(id, description, following, screenName);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
