package com.birbit.android.livecode.twitter.vo;






// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
abstract public class UserBase {

    @com.google.gson.annotations.SerializedName( "id_str" )
    protected String id;
    protected String description;
    protected Boolean following;
    @com.google.gson.annotations.SerializedName( "screen_name" )
    protected String screenName;




    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserBase() {
    }

    public UserBase(String id) {
        this.id = id;
    }

    public UserBase(String id, String description, Boolean following, String screenName) {
        this.id = id;
        this.description = description;
        this.following = following;
        this.screenName = screenName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getFollowing() {
        return following;
    }

    public void setFollowing(Boolean following) {
        this.following = following;
    }

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public void updateNotNull(User other) {
        if(this == other) {
            return;//both came from db, no need to run this.
        }

        if(other.id != null) {
            this.id = other.id;
        }


        if(other.description != null) {
            this.description = other.description;
        }


        if(other.following != null) {
            this.following = other.following;
        }


        if(other.screenName != null) {
            this.screenName = other.screenName;
        }

        // relationships
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public void onBeforeSave() {
        //you can override this method and do some stuff if you want to :)

    }
}
